In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import yfinance as yf
import datetime as dt

### Price and return behaviour

objectives:
- Get daily price data for last 5Y
- Compute daily returns + cumulative returns
- Plot price over time (ine graph) + cumulative returns (histogram)

In [16]:
# Set date range for analysis
end_date = dt.datetime.now()
start_date = end_date - dt.timedelta(days=365*5)  

end_date, start_date

(datetime.datetime(2025, 12, 30, 22, 48, 27, 405848),
 datetime.datetime(2020, 12, 31, 22, 48, 27, 405848))

In [17]:
# Download historical stock data for TTWO
stocks = ['TTWO']
data = yf.download(stocks, start=start_date, end=end_date)
data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open   Volume
Ticker            TTWO        TTWO        TTWO        TTWO     TTWO
Date
2021-01-04  201.850006  208.669998  199.039993  208.669998  1849900
2021-01-05  204.740005  205.080002  200.119995  202.110001   878000
2021-01-06  201.529999  206.639999  199.899994  202.449997  1140400
2021-01-07  208.009995  208.610001  203.199997  204.389999   944200
2021-01-08  210.429993  211.440002  207.630005  209.070007   899700

In [ ]:
# Select 'Close' prices
close_prices = data['Close']
close_prices.head()

In [ ]:
# Plot daily close prices
close_prices.plot(title='Price over time',figsize=(8,8))

In [ ]:
# Calculate daily returns
log_daily_returns = np.log(close_prices/close_prices.shift(1))
log_daily_returns.head()

Ticker          TTWO
Date
2021-01-04       NaN
2021-01-05  0.014216
2021-01-06 -0.015803
2021-01-07  0.031648
2021-01-08  0.011567

In [ ]:
# Plot daily returns
log_daily_returns.plot(title='Daily returns 5Y',figsize=(8,8))

In [ ]:
# Calculate cumulative returns

cumulative_data = log_returns.cumsum()
cumulative_data.head()

In [ ]:
# Plot cumulative returns
cumulative_data.plot(title='Cumulative returns 5Y',figsize=(8,8))

### Downside analysis

Objectives:

Identify:
- Worst 5 daily returns
- Worst monthly period
- plot histogram of returns

In [44]:
log_daily_returns.sort_values('TTWO', ascending=False)

Ticker          TTWO
Date
2025-02-07  0.131310
2022-05-17  0.111355
2023-05-18  0.110522
2023-02-07  0.075602
2024-11-07  0.072619
...              ...
2025-11-07 -0.084278
2024-02-09 -0.090598
2022-01-10 -0.140744
2022-11-08 -0.147118
2021-01-04       NaN

[1254 rows x 1 columns]